[package]
name = "access-card"
version = "0.1.0"
authors = ["June <liumy.f@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
